spring:
    application:
        name: card
    data:
        rest:
            base-path: /api

data:
    resources:
        sanguoxiuUrl: "sanguosha/sanguoxiu/zzhead.jpg"
        weiUrl: "sanguosha/wujiang/【魏】戏志才.jpg"
        shuUrl: "sanguosha/wujaing/【蜀】鲍三娘.jpg"
        wuUrl: "sanguosha/wujaing/【吴】孙鲁班.jpg"
        qunUrl: "sanguosha/wujiang/【群】谋貂蝉.jpg"
        shenUrl: "sanguosha.wujiang/【神】荀彧.jpg"

security:
    user:
        name: chenyuiyu
        password: "88888888"